# Generated by Django 4.2.3 on 2023-09-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='created_by',
            new_name='creates_by',
        ),
    ]
